version: "3.9"  # optional since v1.27.0
services:
  writer_client:
    build: "../clients/writer-client/."
    depends_on:
      - back_end
    environment:
      HOST: 'back_end'
    deploy:
      mode: replicated
      replicas: 2
  reader_client:
    build: "../clients/reader-client/."
    depends_on:
      - back_end
    environment:
      HOST: 'back_end'
    deploy:
      mode: replicated
      replicas: 2
  back_end:
    build: "../back-end/."
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: 'mongodb://root:root@mongo:27017/'
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root